version: 1
entrypoints:
  server:
    routes:
      - path: /health
        methods: [GET]
        route_class: ops
      - path: /healthz
        methods: [GET]
        route_class: ops
      - path: /login
        methods: [GET, POST]
        route_class: authn
  superadmin:
    routes:
      - path: /health
        methods: [GET]
        route_class: ops
